### ISSUE TITLE
"Loudness settings don't need to be enabled"

### ISSUE THREAD

**Issue by aerawk** [Falcosc/enable-loudness-equalisation#10]
I was able to successfully use this script about 3 weeks ago and was able to access the Enhancements tabs on my audio device. However, I checked my audio settings today and noticed that the tab was gone. I tried running the script again, but I end up getting the message "Loudness Settings don't need to be enabled" (seems to be falsely indicating that !missingLoudness is evaluating to true) and I'm unable to access the Enhancements tab any longer.

Would it be possible for you to create another script to reset the Loudness EQ settings for a given device? (I imagine it would be changing the values in the $fxPropertiesImport variable back to the default, but I don't know enough about Powershell scripting to feel comfortable trying this myself). 

![image](https://github.com/Falcosc/enable-loudness-equalisation/assets/37137707/bf97185e-7d19-45e9-b712-6a312afd7c94)

**Comment by Falcosc** [comment]
I can add a tab check next week

**Comment by sejkii** [comment]
same here would be nice to have script to reset since I'm unable to access the Enhancements tab any longer.

**Comment by aerawk** [comment]
Update works as expected, thank you so much for the quick fix!
