### ISSUE TITLE
"Could not find any device"

### ISSUE THREAD

**Issue by fraizzo** [Falcosc/enable-loudness-equalisation#15]
Hi, i try to use this script to enable vb-audio cable, but it cannot find the device, i try with name (Hi-Fi Cable Input), with long name (Altoparlanti (VB-Audio Hi-Fi Cable)) but also with the same error. 

I also check in the register and the name is: Hi-Fi Cable Input

What can i try???

**Comment by fraizzo** [comment]
> Hi, i try to use this script to enable vb-audio cable, but it cannot find the device, i try with name (Hi-Fi Cable Input), with long name (Altoparlanti (VB-Audio Hi-Fi Cable)) but also with the same error.
> 
> I also check in the register and the name is: Hi-Fi Cable Input
> 
> What can i try???

`[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\MMDevices\Audio\Render\{ecd9b36d-ff1e-4ea4-a23b-366e0fe2cc4e}\Properties]
"{b3f8fa53-0004-438e-9003-51a46e139bfc},15"=hex:41,00,00,00,01,00,00,00,e7,07,\
  0c,00,03,00,0d,00,0e,00,07,00,05,00,5d,00
"{a45c254e-df1c-4efd-8020-67d146a850e0},2"="Hi-Fi Cable Input"
"{b3f8fa53-0004-438e-9003-51a46e139bfc},6"="VB-Audio Hi-Fi Cable"
"{b3f8fa53-0004-438e-9003-51a46e139bfc},2"="{1}.ROOT\\MEDIA\\0000"
"{83da6326-97a6-4088-9453-a1923f573b29},3"="oem83.inf:3beb73af0c48fa1f:VBCableInst.NT:1.0.3.5:VBAudioHFVAIO"
"{a8b865dd-2e3d-4094-ad97-e593a70c75d6},8"="VBAudioHFVAIO"
"{a8b865dd-2e3d-4094-ad97-e593a70c75d6},5"="oem83.inf"
"{a8b865dd-2e3d-4094-ad97-e593a70c75d6},6"="VBCableInst.NT"`

**Comment by Falcosc** [comment]
What is the full error message? Could be there are some unwanted characters in your device name. The error message prints the name it was looking for.

This is the device detection:
https://github.com/Falcosc/enable-loudness-equalisation/blob/166d8c17b1d68b52d33ea241748dc4b3bc09e9ba/EnableLoudness.ps1#L75-L78

So just manually execute this part to find out what the issue was. And please share what was wrong to help others.
I already double checked space support, and support for spaces works great on my end:

example
```
PS C:\Users\falco> $playbackDeviceName = "HD Audio"
reg query HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\MMDevices\Audio\Render /s /f "$playbackDeviceName" /d

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\MMDevices\Audio\Render\{42f9d470-0b87-455c-ac38-88fde52b7fd6}\Properties
    {b3f8fa53-0004-438e-9003-51a46e139bfc},6    REG_SZ    Conexant HD Audio
```

**Comment by Falcosc** [comment]
@fraizzo you need to run the script as admin, the req query call does not find any audio devices when run as normal user.

**Comment by Falcosc** [comment]
please try out https://raw.githubusercontent.com/Falcosc/enable-loudness-equalisation/a5ee4cef3c04dd658012e0b59616324d36387bb8/EnableLoudness.ps1
