### ISSUE TITLE
Script is stuck at reg query call

### ISSUE THREAD

**Issue by zZMattyP** [Falcosc/enable-loudness-equalisation#17]
been 20 minutes , hasn't done anything... 

![Screenshot 2024-01-05 193951](https://github.com/Falcosc/enable-loudness-equalisation/assets/155787001/2c7edb92-4f9a-4c6a-97a9-fecc1cfa2cd1)

**Comment by Falcosc** [comment]
Execute "Set-PSDebug -Trace 1" in your PowerShell before you run it, and then share the output to understand which command does not finish on your computer.

**Comment by zZMattyP** [comment]
![Screenshot 2024-01-06 102703](https://github.com/Falcosc/enable-loudness-equalisation/assets/155787001/39ef18a5-38c0-4aa1-a341-e99cadef2591)

**Comment by Falcosc** [comment]
Looks like your windows installation has trouble searching your registry to find your audio device.
Copy the last line and type ```
reg query HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\MMDevices\Audio\Render /s /f speakers /d
```
And monitor with task manager to see if your computer gets busy by this call, or if your system is just refusing to search "speakers" in your registry Audio section.

**Comment by Falcosc** [comment]
Interesting, just found out that you need to run this line as admin as well to find anything. Not being admin could be the issue of somebody else who always got the error message "Could not find any device named speakers"
So if you test why your computer does not execute the search, run it as admin as well.

**Comment by Falcosc** [comment]
@zZMattyP I have replaced the req query call with powershell functions. Please try this out and give me feedback:
https://raw.githubusercontent.com/Falcosc/enable-loudness-equalisation/a5ee4cef3c04dd658012e0b59616324d36387bb8/EnableLoudness.ps1

**Comment by zZMattyP** [comment]
@Falcosc  I believe the raw worked , see below... appreciate you digging deep and helping me fix this issue.

![Screenshot 2024-01-06 185045](https://github.com/Falcosc/enable-loudness-equalisation/assets/155787001/36d9508c-d77e-4675-b73e-d17602b7e892)

**Comment by Falcosc** [comment]
Interesting, thanks for testing, I will publish it now.

**Comment by Falcosc** [comment]
@zZMattyP there was a bug in your version. It didn't apply anything.
Please run the fixed one again: https://raw.githubusercontent.com/Falcosc/enable-loudness-equalisation/main/EnableLoudness.ps1
