### ISSUE TITLE
Main Script Not Updated!

### ISSUE THREAD

**Issue by ArtIsWar** [Falcosc/enable-loudness-equalisation#21]
For some reason, the commits added today do not reflect the functioning version of the script. Linked here is the functional [version](https://raw.githubusercontent.com/Falcosc/enable-loudness-equalisation/166d8c17b1d68b52d33ea241748dc4b3bc09e9ba/EnableLoudness.ps1) 

Cheers

**Comment by Falcosc** [comment]
Can you rephrase your question? I don't understand what's wrong.
