### ISSUE TITLE
Not working for Speakers *Realtek(R) Audio* of ROG STRIX G614JV

### ISSUE THREAD

**Issue by arshcaria** [Falcosc/enable-loudness-equalisation#27]
```
Laptop: ROG STRIX G614JV

OS: Windows 11 Pro 23H2

Audio Devices:

- Bluetooth Apple Airpods 2 (WORKING)
- Bluetooth Sony WH-1000XM3 (WORKING)
- Laptop Speaker (NOT WORKING)
```

I tried the scripts with the devices above. All of the devices show the `Enhancements` tab after the script execution. 

The two bluetooth devices works fine then. 

But the `Speaker` device does not have any options in the `Enhancements` tab and the normalization effect seems not working either. 

![image](https://github.com/Falcosc/enable-loudness-equalisation/assets/3211106/5d78882c-a3b3-4fcc-982e-8061fd3074db)

![image](https://github.com/Falcosc/enable-loudness-equalisation/assets/3211106/dfe65c5c-e386-401a-b026-210fb0dcbbaf)

Below is the driver version

![image](https://github.com/Falcosc/enable-loudness-equalisation/assets/3211106/858d6c53-26cc-4a43-a0e5-104855eda563)

**Comment by Falcosc** [comment]
Check https://github.com/Falcosc/enable-loudness-equalisation#known-issues

The last one 
> does not work if your driver doesn't have any enhancements, try a different one

**Comment by THEBOSS619** [comment]
@arshcaria Your laptop have there own propriety EQ sound feature built-in along with Dolby Atmos so it's naturally won't have the generic features that comes with the driver since your laptop ASUS already implemented there own version of it.

So why duplicate a feature or even use generic ones when already ASUS implemented something specifically for your laptops speaker which is superior.

**Comment by arshcaria** [comment]
> @arshcaria Your laptop have there own propriety EQ sound feature built-in along with Dolby Atmos so it's naturally won't have the generic features that comes with the driver since your laptop ASUS already implemented there own version of it.
> 
> So why duplicate a feature or even use generic ones when already ASUS implemented something specifically for your laptops speaker which is superior.

Thank you. I tried the Dolby app and the `Volume Leveler` option seems to do the job.

![image](https://github.com/Falcosc/enable-loudness-equalisation/assets/3211106/079b46c8-d55a-4fd7-9bc7-41f3076a8e57)
