### ISSUE TITLE
Admin Error with Admin PowerShell

### ISSUE THREAD

**Issue by prodbyeagle** [Falcosc/enable-loudness-equalisation#29]
I dont really know why im getting this?

![image](https://github.com/user-attachments/assets/44d1e1c2-f1fb-41ad-8c5e-7201ebc3f7ed)

**Comment by ArtIsWar** [comment]
You're need to run Equalizer APO as LFX/GFX FIRST, then run the falcosc's command. Not an issue with his work at all.

**Comment by Falcosc** [comment]
Interesting that there are usecases where an admin ha no access. 

https://github.com/Falcosc/enable-loudness-equalisation/blob/f4de655353da0c3d9a28840e845f305e053539a4/EnableLoudness.ps1#L76-80

I guess Equilizer APO does change the visibility of the registry keys from System to admin.

Thats why I habe the hack in the PS file, to overwrite System write online Keys. But on most Devices properties are at least readable by admins.

I probably won't add the hack on this check, because it is ugly as hell.
@prodbyeagle could you screenshot the permissions of your Audio renderer registry keys please?

**Comment by prodbyeagle** [comment]
> You're need to run Equalizer APO as LFX/GFX FIRST, then run the falcosc's command. Not an issue with his work at all.

i did i used your setup but this came

**Comment by ArtIsWar** [comment]
This GitHub is not the place for this, my community discord is.

@Falcosc apologies, unique to a setup of mine, not sure why they trickle over here.

**Comment by prodbyeagle** [comment]
i reinstalled everything and i came back 
![image](https://github.com/user-attachments/assets/dcaddaf0-5e1f-40b8-8c28-cba96393006b)

here are the permissions 
![image](https://github.com/user-attachments/assets/57beb8c9-66e6-472a-90fb-8c3de79636a1)

**Comment by ArtIsWar** [comment]
@prodbyeagle Again, these issues aren't with Falcosc's work but with how you're following my guide.

Please take this issue to my discord and not crowd the Git with issues that aren't related to Falcosc's work.

**Comment by prodbyeagle** [comment]
> Please take this issue to my discord and not crowd the Git with issues that aren't related to Falcosc's work.

Alright.

**Comment by Falcosc** [comment]
Screenshot of admin permission of any device below renderer would be interesting

We need any properties folder. Best if you could find your Sound device hidden behind the folder id to screenshot the admin permissions of it's properties folder

**Comment by prodbyeagle** [comment]
![image](https://github.com/user-attachments/assets/8eabc8cf-8710-4089-95ab-56022d0f7aa7)


> Screenshot of admin permission of any device below renderer would be interesting
> 
> We need any properties folder. Best if you could find your Sound device hidden behind the folder id to screenshot the admin permissions of it's properties folder

**Comment by lucr80** [comment]
1 - Is the command in powershell definitive, after restarting the PC the audio settings will be there or do you need to do the scheduled part of tasks?
2 - Do these commands depend on gpedit group policy? In this case they would not work on Windows home.
3 - A note I noticed that even activated in the audio control the Bass settings do not change, you change, but do not change anything in the audio, only when you install the bass and the equalizer. Is that right?

**Comment by Falcosc** [comment]
Depends on how your driver is implemented. So trial and error on every device
