### ISSUE TITLE
error when running script unable to recognize invoke-webrequest 

### ISSUE THREAD

**Issue by ToxicD3mon** [Falcosc/enable-loudness-equalisation#36]
hello when i try to run the script i get this message was wondering if you can help. Thank you 
![image](https://github.com/user-attachments/assets/f799334b-7017-45a3-a4b5-2ecbe948f669)

**Comment by Falcosc** [comment]
PowerShell is too old in your case, does not work with v1.0
But if you google "The term 'Invoke-WebRequest' is not recognized as the name of a cmdlet" this is not the only possible issue, there are also new PowerShell versions with reduced set of cmdlets out in the wild.

So run with a newer version of Powershell and make sure your installation did not exclude required cmdlets

**Comment by ToxicD3mon** [comment]
okay how do i download a new version of powershell that’ll run that command
? or which version should i download can you send me a link for one please ?

**Comment by Falcosc** [comment]
That would be a question for a Microsoft community. Normally it is already installed. I don't have any resources for you, I would also have to search on the internet how to do it if your windows has a very strange default PS version. Normally "powershell" links to the latest version, but not on your installation.
